theme: jekyll-theme-cayman  # Choose the theme you prefer

# Plugins section (using supported plugins for GitHub Pages)
plugins:
  - jekyll-seo-tag       # For SEO-friendly meta tags
  - jekyll-feed          # For RSS feed generation
  - jekyll-sitemap       # For generating sitemap
  - jekyll-paginate    
